import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>

            <code className={styles.code}> @freepowder13&nbsp;</code>
          </p>
        </div>

        <div className={styles.center}>
          <h1 className={inter.className}>Free Powder Limited </h1>
          {/*<Image*/}
          {/*  className={styles.logo}*/}
          {/*  src="/next.svg"*/}
          {/*  alt="Next.js Logo"*/}
          {/*  width={180}*/}
          {/*  height={37}*/}
          {/*  priority*/}
          {/*/>*/}
        </div>

        <div className={styles.grid}>
          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Typescript
            </h2>
            <p className={inter.className}>
              {/*Find in-depth information about Next.js features and&nbsp;API.*/}
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Angular
            </h2>
            <p className={inter.className}>
              {/*Learn about Next.js in an interactive course with&nbsp;quizzes!*/}
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              React
            </h2>
            <p className={inter.className}>
              {/*Discover and deploy boilerplate example Next.js&nbsp;projects.*/}
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Node.js
            </h2>
            <p className={inter.className}>
              {/*Instantly deploy your Next.js site to a shareable URL*/}
              {/*with&nbsp;Vercel.*/}
            </p>
          </a>
          <a
              href="#"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Next.js
            </h2>
            <p className={inter.className}>
              {/*Instantly deploy your Next.js site to a shareable URL*/}
              {/*with&nbsp;Vercel.*/}
            </p>
          </a>
          <a
              href="#"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Vue
            </h2>
            <p className={inter.className}>
              {/*Instantly deploy your Next.js site to a shareable URL*/}
              {/*with&nbsp;Vercel.*/}
            </p>
          </a>
          <a
              href="#"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Svelte
            </h2>
            <p className={inter.className}>
              {/*Instantly deploy your Next.js site to a shareable URL*/}
              {/*with&nbsp;Vercel.*/}
            </p>
          </a>
          <a
              href="#"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              MongoDB
            </h2>
            <p className={inter.className}>
              {/*Instantly deploy your Next.js site to a shareable URL*/}
              {/*with&nbsp;Vercel.*/}
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
